apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: beach-hacks-dev-portal
  description: A Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: 'amogh-opsverse/beach-hacks-dev-portal'
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: amoghshiv99@gmai.com
  lifecycle: experimental
